version: '2.2'

services:
  tests:
    restart: 'no'
    build:
      context: .
      args:
        ENV: TEST
    env_file:
      - .env
    environment:
      ENV: TEST
    cpus: 1
    mem_limit: 512m
    volumes:
      - .:/app
    command: "pytest"

  app:
    restart: always
    build:
      context: .
    env_file: .env
    cpus: 2
    mem_limit: 512m
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --reload
  