replicaCount: 2

resources:
  limits:
    cpu: 2
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

service:
  port: 8000

configmap:
  ROOT_PATH: "/v1/calc/pension"

livenessProbe:
  httpGet:
    path: /_health
    port: http

readinessProbe:
  httpGet:
    path: /_health
    port: http

tolerations:
  - key: "yandex.cloud/preemptible"
    effect: NoExecute
    value: "true"

nodeSelector:
  yandex.cloud/preemptible: "true"
